#pragma once
#include <JuceHeader.h>

namespace f64 {

class AIPromptHelper
{
public:
    static juce::String getAIPrompt()
    {
        return
            "You are an expert audio DSP engineer writing a real-time drum synthesizer / audio effect script for FORGE64, a 64-pad modular drum machine and synthesizer plugin.\n\n"
            "## 1. Engine & Runtime Architecture\n"
            "- Language: Lua 5.4 in a sandboxed, low-latency audio thread environment.\n"
            "- Entry Point: Your script MUST define a global function `process()` which is executed once per audio block (e.g. 64, 128, 256, 512 samples).\n"
            "- Real-Time Zero Allocation Rule:\n"
            "  * NEVER create tables `{}` or closures `function() ... end` inside `process()`.\n"
            "  * Dynamic allocations inside `process()` force the garbage collector to run on the audio thread, causing audio dropouts.\n"
            "  * Pre-allocate all persistent DSP states (filter variables, oscillators, phase accumulators, envelopes, delay buffers, local accumulation arrays) outside `process()` at module file scope.\n\n"
            "## 2. CPU Budget Constraints & Watchdogs\n"
            "- FORGE64 enforces strict instruction-count watchdogs to protect the audio engine from runaway scripts:\n"
            "  * Script compilation / initialization: 4,000,000 instruction limit.\n"
            "  * Block execution `process()`: 8,000,000 instruction limit.\n"
            "- Sorting & Initialization Rule:\n"
            "  * NEVER write manual $O(N^2)$ loops (e.g. insertion sort) over large arrays during initialization.\n"
            "  * ALWAYS use Lua's native C quicksort: `table.sort(my_table, function(a, b) return a.f < b.f end)` (runs in < 0.05 ms).\n"
            "  * Only generate the number of modes/elements needed (e.g. 32 to 64 modes).\n\n"
            "## 3. Audio I/O & Local Buffer Accumulation (CRITICAL PERFORMANCE RULE)\n"
            "- `inL(i)` / `inR(i)`    : Read incoming audio sample at index `i` (0 <= i < n).\n"
            "- `outL(i, v)` / `outR(i, v)`: Write output audio sample `v` at index `i` (0 <= i < n).\n"
            "- CRITICAL RULE: Calling `outL`/`outR` or `inL`/`inR` crosses the C++/Lua boundary.\n"
            "  * NEVER call `outL` or `outR` inside an inner loop over multiple modes or oscillators!\n"
            "    (Doing so for 64 modes over 512 samples creates 65,000+ C calls and will breach the CPU budget).\n"
            "  * ALWAYS pre-allocate local accumulation buffers at file scope:\n"
            "    ```lua\n"
            "    local accL = {}\n"
            "    local accR = {}\n"
            "    for i = 0, 1024 do accL[i] = 0.0; accR[i] = 0.0 end\n"
            "    ```\n"
            "  * In `process()`, zero `accL` and `accR` from 0 to n-1, accumulate your oscillators/modes into `accL[i]` and `accR[i]` using fast local table indexing, and call `outL(i, finalL)` and `outR(i, finalR)` EXACTLY ONCE per sample at the master output stage!\n\n"
            "## 4. Global Variables (Updated Every Block by Host)\n"
            "- `n`      : Integer block size in samples (e.g. 64, 128, 256, 512).\n"
            "- `sr`     : Float sample rate in Hz (e.g. 44100.0, 48000.0, 96000.0).\n"
            "- `vel`    : Float trigger velocity in range [0.01, 1.0].\n"
            "- `age`    : Float hit age in seconds since trigger onset.\n"
            "- `trig`   : Boolean true ONLY on the first block of a hit (from MIDI, step sequencer, or pad tap). Use `if trig then` to reset phases, trigger envelopes, strike modal resonators, and seed PRNGs.\n"
            "- `note`   : Integer MIDI note number (0 to 127, middle C = 60).\n\n"
            "## 5. Parameter API\n"
            "- `param(\"name\")`: Read real-time pad parameter (smoothed by host):\n"
            "  * `\"tune\"` or `\"pitch\"` : Semitones pitch offset (-24.0 to +24.0).\n"
            "  * `\"decay\"` or `\"dec\"`  : Decay time in seconds (0.005 to 8.0).\n"
            "  * `\"drive\"` or `\"drv\"`  : Drive / saturation amount (0.0 to 1.0).\n"
            "  * `\"p1\"` or `\"fx1\"`     : Module Macro 1 knob (0.0 to 1.0) [e.g. Punch / Bright / Tone].\n"
            "  * `\"p2\"` or `\"fx2\"`     : Module Macro 2 knob (0.0 to 1.0) [e.g. Shimmer / Click / Metal].\n"
            "  * `\"p3\"` or `\"fx3\"`     : Module Macro 3 knob (0.0 to 1.0) [e.g. Hit Pos / Sub / Spread].\n"
            "  * `\"p4\"` or `\"fx4\"`     : Module Macro 4 knob (0.0 to 1.0) [e.g. Choke / Air / Reson].\n"
            "  * `\"p5\"` or `\"fx5\"`     : Module Macro 5 knob (0.0 to 1.0) [e.g. Character / Noise / Custom].\n"
            "  * `\"level\"`             : Pad level (0.0 to 1.0).\n"
            "  * `\"pan\"`               : Pad pan (-1.0 to +1.0).\n\n"
            "## 6. Built-in Math & Fast PRNG\n"
            "- Fast PRNG         : `rnd()` returning [0.0, 1.0), `rnd(max)` returning [0.0, max), `rnd(min, max)` returning [min, max).\n"
            "- Standard Math     : `sin`, `cos`, `tan`, `asin`, `acos`, `atan`, `atan2`, `exp`, `log`, `log10`, `pow`, `sqrt`, `abs`, `floor`, `ceil`, `min`, `max`, `clamp`, `round`, `sign`.\n"
            "- Saturation/Warmth : `tanh`, `sinh`, `cosh` (great for tape drive and soft-clipping saturation).\n"
            "- Constants         : `pi` (3.141592653589793).\n"
            "- Table Functions   : `table.sort`, `table.insert`, `table.remove`.\n\n"
            "## 7. Anti-Click & Transient Best Practices\n"
            "- Fast Exponential Attacks: Always taper sudden pitch drops or noise bursts with a sub-millisecond attack curve (e.g. `1.0 - exp(-t / 0.0005)`) to eliminate DC offsets and audio pops.\n"
            "- Denormal Prevention: In feedback paths (such as Karplus-Strong string delays, allpass chains, and reverb loops), flush values below `1e-7` to zero (`if abs(val) < 1e-7 then val = 0.0 end`).\n"
            "- Soft Peak Limiting: Always wrap final module output through `tanh` soft saturation to ensure acoustic signals clip gracefully without harsh digital distortion when high drive or resonance is dialed in.\n"
            "- Modulation Integration: Remember that every parameter (`tune`, `decay`, `drive`, and `p1` to `p5`) is fully modulatable in real time by FORGE64's 10 LFOs, 4 Chaos generators, 4 Envelopes, and Sequencer Parameter Locks.\n\n"
            "## 8. Modal & Physical Modeling Recommendations\n"
            "- Optimal Mode Count: 32 to 64 modes.\n"
            "- 64 physical resonators combined with non-linear modal cross-coupling (energy transfer between modes) and a stochastic HF residual noise wash produces an ultra-realistic acoustic crash, ride, bell, or plate at under 2% CPU.\n\n"
            "## 9. Plug & Play Templates\n\n"
            "### Template A: Analog / Subtractive / FM Drum Module (5 Macros)\n"
            "```lua\n"
            "local phase = 0.0\n"
            "local env = 0.0\n\n"
            "function process()\n"
            "  local dt = 1.0 / sr\n"
            "  local tune     = param(\"tune\")\n"
            "  local decay    = param(\"decay\")\n"
            "  local punch    = param(\"p1\") -- Macro 1: Pitch sweep depth\n"
            "  local click    = param(\"p2\") -- Macro 2: Attack transient click\n"
            "  local sub      = param(\"p3\") -- Macro 3: Low-end body reinforcement\n"
            "  local warmth   = param(\"p4\") -- Macro 4: Harmonic saturation\n"
            "  local tailBend = param(\"p5\") -- Macro 5: Tail glide / modulation\n"
            "  local drive    = param(\"drive\")\n\n"
            "  if trig then\n"
            "    phase = 0.0\n"
            "    env = 1.0\n"
            "  end\n\n"
            "  local baseFreq = 55.0 * (2.0 ^ (tune / 12.0))\n"
            "  local decayRate = exp(-dt / (decay * 0.5 + 0.01))\n\n"
            "  for i = 0, n - 1 do\n"
            "    env = env * decayRate\n"
            "    local sag = 1.0 - tailBend * 0.25 * (1.0 - env)\n"
            "    local pitchMod = baseFreq * (1.0 + punch * 4.0 * (env ^ 2)) * sag\n"
            "    phase = (phase + pitchMod * dt) % 1.0\n\n"
            "    local body = sin(phase * 2.0 * pi) * env * vel\n"
            "    if warmth > 0.02 then\n"
            "      body = body + sin(phase * 4.0 * pi) * (warmth * 0.35) * env\n"
            "    end\n\n"
            "    local subSig = sin(phase * pi) * sub * env * 0.8\n"
            "    local clickSmp = (trig and i < 24) and ((rnd() * 2.0 - 1.0) * (0.3 + click * 1.2) * vel) or 0.0\n"
            "    local sig = body + subSig + clickSmp\n\n"
            "    local totDrive = drive + warmth * 0.2\n"
            "    if totDrive > 0.01 then sig = tanh(sig * (1.0 + totDrive * 4.0)) end\n\n"
            "    outL(i, sig)\n"
            "    outR(i, sig)\n"
            "  end\n"
            "end\n"
            "```\n\n"
            "### Template B: Physical Modal / Multi-Resonator Module (Buffered Accumulator, 5 Macros)\n"
            "```lua\n"
            "local NUM_MODES = 48\n"
            "local mode_f = {}\n"
            "local mode_r = {}\n"
            "local mode_q = {}\n"
            "local accL = {}\n"
            "local accR = {}\n"
            "for i = 0, 1024 do accL[i] = 0.0; accR[i] = 0.0 end\n\n"
            "do\n"
            "  local raw = {}\n"
            "  for m = 1, NUM_MODES do\n"
            "    raw[m] = { f = 200.0 * (m ^ 1.35) * (0.98 + rnd() * 0.04) }\n"
            "  end\n"
            "  table.sort(raw, function(a, b) return a.f < b.f end)\n"
            "  for m = 1, NUM_MODES do\n"
            "    mode_f[m] = raw[m].f\n"
            "    mode_r[m] = 0.0\n"
            "    mode_q[m] = 0.0\n"
            "  end\n"
            "end\n\n"
            "function process()\n"
            "  local dt = 1.0 / sr\n"
            "  local tune       = param(\"tune\")\n"
            "  local decay      = max(0.05, param(\"decay\"))\n"
            "  local brightness = param(\"p1\") -- Macro 1: Mode brightness tilt\n"
            "  local shimmer    = param(\"p2\") -- Macro 2: HF noise shimmer\n"
            "  local hitPos     = param(\"p3\") -- Macro 3: Strike position weighting\n"
            "  local damping    = param(\"p4\") -- Macro 4: Damping / choke\n"
            "  local spread     = param(\"p5\") -- Macro 5: Stereo width spread\n"
            "  local drive      = param(\"drive\")\n"
            "  local pitchMult  = 2.0 ^ (tune / 12.0)\n\n"
            "  for i = 0, n - 1 do accL[i] = 0.0; accR[i] = 0.0 end\n\n"
            "  if trig then\n"
            "    for m = 1, NUM_MODES do\n"
            "      local posFactor = (m < 16) and (1.0 - hitPos * 0.4) or (0.5 + hitPos * 0.7)\n"
            "      local impulse = (vel ^ 1.2) * (1.0 / sqrt(m)) * posFactor\n"
            "      mode_r[m] = mode_r[m] + impulse\n"
            "    end\n"
            "  end\n\n"
            "  for m = 1, NUM_MODES do\n"
            "    local r = mode_r[m]\n"
            "    local q = mode_q[m]\n"
            "    if abs(r) + abs(q) > 1e-9 then\n"
            "      local f = min(sr * 0.45, mode_f[m] * pitchMult)\n"
            "      local damp = exp(-6.907755 / (decay * (1.2 - damping * 0.7) * (1.0 / sqrt(m)) * sr))\n"
            "      local w = 2.0 * pi * f * dt\n"
            "      local c = cos(w) * damp\n"
            "      local s = sin(w) * damp\n"
            "      local panL = 0.5 - spread * 0.4 * ((m % 2 == 0) and 1.0 or -1.0)\n"
            "      local panR = 1.0 - panL\n\n"
            "      for i = 0, n - 1 do\n"
            "        local nr = r * c - q * s\n"
            "        q = r * s + q * c\n"
            "        r = nr\n"
            "        accL[i] = accL[i] + r * panL\n"
            "        accR[i] = accR[i] + r * panR\n"
            "      end\n"
            "      mode_r[m] = r\n"
            "      mode_q[m] = q\n"
            "    end\n"
            "  end\n\n"
            "  local env = exp(-age / decay)\n"
            "  for i = 0, n - 1 do\n"
            "    local nz = (rnd() * 2.0 - 1.0) * shimmer * 0.2 * env\n"
            "    local sL = (accL[i] + nz) * vel * 2.5\n"
            "    local sR = (accR[i] + nz) * vel * 2.5\n"
            "    if drive > 0.01 then\n"
            "      sL = tanh(sL * (1.0 + drive * 3.5))\n"
            "      sR = tanh(sR * (1.0 + drive * 3.5))\n"
            "    end\n"
            "    outL(i, sL)\n"
            "    outR(i, sR)\n"
            "  end\n"
            "end\n"
            "```\n\n"
            "Please generate an authentic, rich drum synthesizer or percussion algorithm for [INSTRUMENT / SOUND DESCRIPTION] following this exact API, performance rules, and real-time conventions.";
    }

    static void copyPromptToClipboard()
    {
        juce::SystemClipboard::copyTextToClipboard(getAIPrompt());
    }

    static void showAIPromptDialog(juce::Component* parent = nullptr)
    {
        copyPromptToClipboard();

        auto* w = new juce::AlertWindow("FORGE64 // AI AGENT PROMPT COPIED",
                                        "The master prompt has been COPIED to your clipboard!\n\n"
                                        "You can paste this directly into ChatGPT, Claude, Antigravity, or any LLM "
                                        "to generate custom plug-and-play Lua drum DSP modules for FORGE64.",
                                        juce::AlertWindow::InfoIcon, parent);

        w->addButton("Copy Again", 1, juce::KeyPress(juce::KeyPress::returnKey));
        w->addButton("Close", 0, juce::KeyPress(juce::KeyPress::escapeKey));

        w->enterModalState(true, juce::ModalCallbackFunction::create([w](int result)
        {
            if (result == 1)
                copyPromptToClipboard();
            delete w;
        }));
    }
};

} // namespace f64
